### PR TITLE
trim down the list of short names

### PR DESCRIPTION
**Pull request by vrothberg**
Trim down the list of short names.  Projects like "audacity" should  
choose a propper home on their own.  Also, for now, remove the "f*/*"
entries.                                                             

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @fatherlinux PTAL

**Comment by mheon** [comment]
I think you were a little too aggressive - we should definitely keep the
toolbox images, for example. The specific version-prefixed images may also
be alright, since we're not squatting on the actually name.

**Comment by rhatdan** [comment]
@vrothberg I agree leave the f*/IMAGEs since these are Fedora specific.
Also leave toolbox.

**Comment by vrothberg** [comment]
> @vrothberg I agree leave the f*/IMAGEs since these are Fedora specific.

I fear the list could quickly turn into a unmanageable behemoth if we keep all possible images. If each distro would do it for each release, the list would grow very quickly.

I am open to be convinced of a need to have these images but listing everything on a registry is hard to maintain and may waste cycles (each item needs to be parsed on each invocation of Podman, Buildah and friends).

> Also leave toolbox.

Shouldn't the toolbox team decide how they want to resolve?

**Comment by rhatdan** [comment]
We we should only parse on the first pull or an image.  How long does it take to parse a few thousand lines?

Perhaps this is a case for the glob parsing we had talked about where you would know that images that start with f33/* were always to be pulled from registry.fedoraproject.org.

**Comment by vrothberg** [comment]
> We we should only parse on the first pull or an image. How long does it take to parse a few thousand lines?

It's pretty cheap but I still gravitate towards a short list rather than an extensive one. User can still be prompted.

**Comment by vrothberg** [comment]
Rebased

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
