### PR TITLE
Added UBI new UBI Short names

### PR DESCRIPTION
**Pull request by fatherlinux**

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by jamescassell** [comment]
```
Trying to pull registry.access.redhat.com/ubi8-micro:latest...
  name unknown: Repo not found
Error: Error initializing source docker://registry.access.redhat.com/ubi8-micro:latest: Error reading manifest latest in registry.access.redhat.com/ubi8-micro: name unknown: Repo not found
```

**Comment by fatherlinux** [comment]
> ```
> Trying to pull registry.access.redhat.com/ubi8-micro:latest...
>   name unknown: Repo not found
> Error: Error initializing source docker://registry.access.redhat.com/ubi8-micro:latest: Error reading manifest latest in registry.access.redhat.com/ubi8-micro: name unknown: Repo not found
> ```

It's a sneak peak. We need it here before we publish the image :-) There's a chicken and egg problem.

**Pull request merged**
