### PR TITLE
Add a number of OTel-related containers to the registry.

### PR DESCRIPTION
**Pull request by michaelsafyan**
[Open Telemetry (OTel)](https://opentelemetry.io/) is a vendor-neutral,  [CNCF project](https://www.cncf.io/projects/opentelemetry/) related to instrumentation.

Remove friction for users of OTel by ensuring that failure to resolve the container short name is not an issue (where the `containers/shortnames` repo is being used to resolve short name aliases).

This includes frequently downloaded containers in https://hub.docker.com/u/otel with recent updates. Some demo-oriented containers, containers not updated recently, and containers with low download counts have been omitted.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing, @michaelsafyan !

To pass the DCO CI job, can you add the "Signed-off-by" line to the commit?  You can do that via `git commit -s --amend` and repush.

@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM, we can merge once the Commit is signed.

**Comment by michaelsafyan** [comment]
Thanks. I ran into an issue when attempting to re-push but managed to resolve it, though I'm uncertain if I did so correctly.

**Review by vrothberg — APPROVED** [review]
The commits look good.  Thank you!

**Pull request merged**
